spring:
    application:
        name: Card-Processing-Service
    datasource:
        url: your_db_url
        username: your_db_username
        password: your_db_password
        driverClassName: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
    data:
        redis:
            host: localhost
            port: 6379

jwt:
    secretKey: your_64_length_char_string_for_jwt_key